binaryAnd = true and false
binaryAndOr = true and false or true
binaryOrAnd = false or true and false

plusMinus = 1 + 2 - 3
minusPlus = 4 - 5 + 6
mixedArithmetic = 7 + 8 - 9 * 10 / 11 + 12 // 13 % 14 ** 15 ** 16

allOperators =
    1 * 2 + 3 - 4 / 5 == 6 != 7 < 8 <= 9 > 10 and 
    11 or 12 |> 13 |> 15 // 16 % 17 ** 18  ** 19 >= 20 or
    not not
    not notand and
    not - 22 - -23 +-+-+-24

(*
allOperators =
    ((((((((((((1 * 2) + 3) - (4 / 5)) == 6) != 7) < 8) <= 9) > 10) and 
    11) or 12) |> 13) |> ((((15 // 16) % (17 ** (18  ** 19))) >= 20) or
    ((not (not
    (not notand))) and
    (not (((- 22) - (-23)) +(-(+(-(+(-24))))))))))
*)

(*
Token(type=SYMBOL, value="binaryAnd", position=(1, 1, 0))
Token(type=ASSIGN, value="=", position=(1, 11, 0))
Token(type=TRUE, value="true", position=(1, 13, 0))
Token(type=AND, value="and", position=(1, 18, 0))
Token(type=FALSE, value="false", position=(1, 22, 0))
Token(type=SYMBOL, value="binaryAndOr", position=(2, 1, 0))
Token(type=ASSIGN, value="=", position=(2, 13, 0))
Token(type=TRUE, value="true", position=(2, 15, 0))
Token(type=AND, value="and", position=(2, 20, 0))
Token(type=FALSE, value="false", position=(2, 24, 0))
Token(type=OR, value="or", position=(2, 30, 0))
Token(type=TRUE, value="true", position=(2, 33, 0))
Token(type=SYMBOL, value="binaryOrAnd", position=(3, 1, 0))
Token(type=ASSIGN, value="=", position=(3, 13, 0))
Token(type=FALSE, value="false", position=(3, 15, 0))
Token(type=OR, value="or", position=(3, 21, 0))
Token(type=TRUE, value="true", position=(3, 24, 0))
Token(type=AND, value="and", position=(3, 29, 0))
Token(type=FALSE, value="false", position=(3, 33, 0))
Token(type=SYMBOL, value="plusMinus", position=(5, 1, 0))
Token(type=ASSIGN, value="=", position=(5, 11, 0))
Token(type=INTEGER_LITERAL, value="1", position=(5, 13, 0))
Token(type=PLUS, value="+", position=(5, 15, 0))
Token(type=INTEGER_LITERAL, value="2", position=(5, 17, 0))
Token(type=MINUS, value="-", position=(5, 19, 0))
Token(type=INTEGER_LITERAL, value="3", position=(5, 21, 0))
Token(type=SYMBOL, value="minusPlus", position=(6, 1, 0))
Token(type=ASSIGN, value="=", position=(6, 11, 0))
Token(type=INTEGER_LITERAL, value="4", position=(6, 13, 0))
Token(type=MINUS, value="-", position=(6, 15, 0))
Token(type=INTEGER_LITERAL, value="5", position=(6, 17, 0))
Token(type=PLUS, value="+", position=(6, 19, 0))
Token(type=INTEGER_LITERAL, value="6", position=(6, 21, 0))
Token(type=SYMBOL, value="mixedArithmetic", position=(7, 1, 0))
Token(type=ASSIGN, value="=", position=(7, 17, 0))
Token(type=INTEGER_LITERAL, value="7", position=(7, 19, 0))
Token(type=PLUS, value="+", position=(7, 21, 0))
Token(type=INTEGER_LITERAL, value="8", position=(7, 23, 0))
Token(type=MINUS, value="-", position=(7, 25, 0))
Token(type=INTEGER_LITERAL, value="9", position=(7, 27, 0))
Token(type=MULTIPLY, value="*", position=(7, 29, 0))
Token(type=INTEGER_LITERAL, value="10", position=(7, 31, 0))
Token(type=DIVIDE, value="/", position=(7, 34, 0))
Token(type=INTEGER_LITERAL, value="11", position=(7, 36, 0))
Token(type=PLUS, value="+", position=(7, 39, 0))
Token(type=INTEGER_LITERAL, value="12", position=(7, 41, 0))
Token(type=FLOOR_DIVIDE, value="//", position=(7, 44, 0))
Token(type=INTEGER_LITERAL, value="13", position=(7, 47, 0))
Token(type=MODULO, value="%", position=(7, 50, 0))
Token(type=INTEGER_LITERAL, value="14", position=(7, 52, 0))
Token(type=EXPONENTIATION, value="**", position=(7, 55, 0))
Token(type=INTEGER_LITERAL, value="15", position=(7, 58, 0))
Token(type=EXPONENTIATION, value="**", position=(7, 61, 0))
Token(type=INTEGER_LITERAL, value="16", position=(7, 64, 0))
Token(type=SYMBOL, value="allOperators", position=(9, 1, 0))
Token(type=ASSIGN, value="=", position=(9, 14, 0))
Token(type=INTEGER_LITERAL, value="1", position=(10, 5, 4))
Token(type=MULTIPLY, value="*", position=(10, 7, 4))
Token(type=INTEGER_LITERAL, value="2", position=(10, 9, 4))
Token(type=PLUS, value="+", position=(10, 11, 4))
Token(type=INTEGER_LITERAL, value="3", position=(10, 13, 4))
Token(type=MINUS, value="-", position=(10, 15, 4))
Token(type=INTEGER_LITERAL, value="4", position=(10, 17, 4))
Token(type=DIVIDE, value="/", position=(10, 19, 4))
Token(type=INTEGER_LITERAL, value="5", position=(10, 21, 4))
Token(type=EQUAL, value="==", position=(10, 23, 4))
Token(type=INTEGER_LITERAL, value="6", position=(10, 26, 4))
Token(type=NOT_EQUAL, value="!=", position=(10, 28, 4))
Token(type=INTEGER_LITERAL, value="7", position=(10, 31, 4))
Token(type=LESS_THAN, value="<", position=(10, 33, 4))
Token(type=INTEGER_LITERAL, value="8", position=(10, 35, 4))
Token(type=LESS_THAN_EQUAL, value="<=", position=(10, 37, 4))
Token(type=INTEGER_LITERAL, value="9", position=(10, 40, 4))
Token(type=GREATER_THAN, value=">", position=(10, 42, 4))
Token(type=INTEGER_LITERAL, value="10", position=(10, 44, 4))
Token(type=AND, value="and", position=(10, 47, 4))
Token(type=INTEGER_LITERAL, value="11", position=(11, 5, 4))
Token(type=OR, value="or", position=(11, 8, 4))
Token(type=INTEGER_LITERAL, value="12", position=(11, 11, 4))
Token(type=PIPE, value="|>", position=(11, 14, 4))
Token(type=INTEGER_LITERAL, value="13", position=(11, 17, 4))
Token(type=PIPE, value="|>", position=(11, 20, 4))
Token(type=INTEGER_LITERAL, value="15", position=(11, 23, 4))
Token(type=FLOOR_DIVIDE, value="//", position=(11, 26, 4))
Token(type=INTEGER_LITERAL, value="16", position=(11, 29, 4))
Token(type=MODULO, value="%", position=(11, 32, 4))
Token(type=INTEGER_LITERAL, value="17", position=(11, 34, 4))
Token(type=EXPONENTIATION, value="**", position=(11, 37, 4))
Token(type=INTEGER_LITERAL, value="18", position=(11, 40, 4))
Token(type=EXPONENTIATION, value="**", position=(11, 44, 4))
Token(type=INTEGER_LITERAL, value="19", position=(11, 47, 4))
Token(type=GREATER_THAN_EQUAL, value=">=", position=(11, 50, 4))
Token(type=INTEGER_LITERAL, value="20", position=(11, 53, 4))
Token(type=OR, value="or", position=(11, 56, 4))
Token(type=NOT, value="not", position=(12, 5, 4))
Token(type=NOT, value="not", position=(12, 9, 4))
Token(type=NOT, value="not", position=(13, 5, 4))
Token(type=SYMBOL, value="notand", position=(13, 9, 4))
Token(type=AND, value="and", position=(13, 16, 4))
Token(type=NOT, value="not", position=(14, 5, 4))
Token(type=MINUS, value="-", position=(14, 9, 4))
Token(type=INTEGER_LITERAL, value="22", position=(14, 11, 4))
Token(type=MINUS, value="-", position=(14, 14, 4))
Token(type=MINUS, value="-", position=(14, 16, 4))
Token(type=INTEGER_LITERAL, value="23", position=(14, 17, 4))
Token(type=PLUS, value="+", position=(14, 20, 4))
Token(type=MINUS, value="-", position=(14, 21, 4))
Token(type=PLUS, value="+", position=(14, 22, 4))
Token(type=MINUS, value="-", position=(14, 23, 4))
Token(type=PLUS, value="+", position=(14, 24, 4))
Token(type=MINUS, value="-", position=(14, 25, 4))
Token(type=INTEGER_LITERAL, value="24", position=(14, 26, 4))
Token(type=SYMBOL, value="plusMinusPlus", position=(150, 1, 0))
Token(type=ASSIGN, value="=", position=(150, 15, 0))
Token(type=INTEGER_LITERAL, value="1", position=(150, 17, 0))
Token(type=PLUS, value="+", position=(150, 19, 0))
Token(type=INTEGER_LITERAL, value="2", position=(150, 21, 0))
Token(type=MINUS, value="-", position=(150, 23, 0))
Token(type=INTEGER_LITERAL, value="3", position=(150, 25, 0))
Token(type=PLUS, value="+", position=(150, 27, 0))
Token(type=INTEGER_LITERAL, value="4", position=(150, 29, 0))
Token(type=EOF, value="", position=(150, 30, 0))
*)

plusMinusPlus = 1 + 2 - 3 + 4