noArgs = func(    )
singleArg = func(42)
singleArgTrailingComma = func(
    42,
)

multipleArgs = func(1, 2, 3)
nestedFunctionCalls = outerFunc(innerFunc1(10), innerFunc2(20, 30))

methodCall = obj.method(100, "test")
chainedMethodCalls = obj.firstMethod().secondMethod(200).thirdMethod("chain")

namedArgs = func(arg1=10, arg2="hello", arg3=true)
mixedArgs = func(5, arg1="value", 10, arg2="another")

callOfCallOfCall = func1()(func2())(func3()(100))

(*
Token(type=SYMBOL, value='noArgs', position=(1, 1, 0))
Token(type=ASSIGN, value='=', position=(1, 8, 0))
Token(type=SYMBOL, value='func', position=(1, 10, 0))
Token(type=FUNCTION_CALL_START, value='(', position=(1, 14, 0))
Token(type=FUNCTION_CALL_END, value=')', position=(1, 19, 0))
Token(type=SYMBOL, value='singleArg', position=(2, 1, 0))
Token(type=ASSIGN, value='=', position=(2, 11, 0))
Token(type=SYMBOL, value='func', position=(2, 13, 0))
Token(type=FUNCTION_CALL_START, value='(', position=(2, 17, 0))
Token(type=INTEGER_LITERAL, value='42', position=(2, 18, 0))
Token(type=FUNCTION_CALL_END, value=')', position=(2, 20, 0))
Token(type=SYMBOL, value='singleArgTrailingComma', position=(3, 1, 0))
Token(type=ASSIGN, value='=', position=(3, 24, 0))
Token(type=SYMBOL, value='func', position=(3, 26, 0))
Token(type=FUNCTION_CALL_START, value='(', position=(3, 30, 0))
Token(type=INTEGER_LITERAL, value='42', position=(4, 5, 4))
Token(type=COMMA, value=',', position=(4, 7, 4))
Token(type=FUNCTION_CALL_END, value=')', position=(5, 1, 0))
Token(type=SYMBOL, value='multipleArgs', position=(7, 1, 0))
Token(type=ASSIGN, value='=', position=(7, 14, 0))
Token(type=SYMBOL, value='func', position=(7, 16, 0))
Token(type=FUNCTION_CALL_START, value='(', position=(7, 20, 0))
Token(type=INTEGER_LITERAL, value='1', position=(7, 21, 0))
Token(type=COMMA, value=',', position=(7, 22, 0))
Token(type=INTEGER_LITERAL, value='2', position=(7, 24, 0))
Token(type=COMMA, value=',', position=(7, 25, 0))
Token(type=INTEGER_LITERAL, value='3', position=(7, 27, 0))
Token(type=FUNCTION_CALL_END, value=')', position=(7, 28, 0))
Token(type=SYMBOL, value='nestedFunctionCalls', position=(8, 1, 0))
Token(type=ASSIGN, value='=', position=(8, 21, 0))
Token(type=SYMBOL, value='outerFunc', position=(8, 23, 0))
Token(type=FUNCTION_CALL_START, value='(', position=(8, 32, 0))
Token(type=SYMBOL, value='innerFunc1', position=(8, 33, 0))
Token(type=FUNCTION_CALL_START, value='(', position=(8, 43, 0))
Token(type=INTEGER_LITERAL, value='10', position=(8, 44, 0))
Token(type=FUNCTION_CALL_END, value=')', position=(8, 46, 0))
Token(type=COMMA, value=',', position=(8, 47, 0))
Token(type=SYMBOL, value='innerFunc2', position=(8, 49, 0))
Token(type=FUNCTION_CALL_START, value='(', position=(8, 59, 0))
Token(type=INTEGER_LITERAL, value='20', position=(8, 60, 0))
Token(type=COMMA, value=',', position=(8, 62, 0))
Token(type=INTEGER_LITERAL, value='30', position=(8, 64, 0))
Token(type=FUNCTION_CALL_END, value=')', position=(8, 66, 0))
Token(type=FUNCTION_CALL_END, value=')', position=(8, 67, 0))
Token(type=SYMBOL, value='methodCall', position=(10, 1, 0))
Token(type=ASSIGN, value='=', position=(10, 12, 0))
Token(type=SYMBOL, value='obj', position=(10, 14, 0))
Token(type=DOT, value='.', position=(10, 17, 0))
Token(type=SYMBOL, value='method', position=(10, 18, 0))
Token(type=FUNCTION_CALL_START, value='(', position=(10, 24, 0))
Token(type=INTEGER_LITERAL, value='100', position=(10, 25, 0))
Token(type=COMMA, value=',', position=(10, 28, 0))
Token(type=STRING_LITERAL, value='test', position=(10, 30, 0))
Token(type=FUNCTION_CALL_END, value=')', position=(10, 36, 0))
Token(type=SYMBOL, value='chainedMethodCalls', position=(11, 1, 0))
Token(type=ASSIGN, value='=', position=(11, 20, 0))
Token(type=SYMBOL, value='obj', position=(11, 22, 0))
Token(type=DOT, value='.', position=(11, 25, 0))
Token(type=SYMBOL, value='firstMethod', position=(11, 26, 0))
Token(type=FUNCTION_CALL_START, value='(', position=(11, 37, 0))
Token(type=FUNCTION_CALL_END, value=')', position=(11, 38, 0))
Token(type=DOT, value='.', position=(11, 39, 0))
Token(type=SYMBOL, value='secondMethod', position=(11, 40, 0))
Token(type=FUNCTION_CALL_START, value='(', position=(11, 52, 0))
Token(type=INTEGER_LITERAL, value='200', position=(11, 53, 0))
Token(type=FUNCTION_CALL_END, value=')', position=(11, 56, 0))
Token(type=DOT, value='.', position=(11, 57, 0))
Token(type=SYMBOL, value='thirdMethod', position=(11, 58, 0))
Token(type=FUNCTION_CALL_START, value='(', position=(11, 69, 0))
Token(type=STRING_LITERAL, value='chain', position=(11, 70, 0))
Token(type=FUNCTION_CALL_END, value=')', position=(11, 77, 0))
Token(type=SYMBOL, value='namedArgs', position=(13, 1, 0))
Token(type=ASSIGN, value='=', position=(13, 11, 0))
Token(type=SYMBOL, value='func', position=(13, 13, 0))
Token(type=FUNCTION_CALL_START, value='(', position=(13, 17, 0))
Token(type=SYMBOL, value='arg1', position=(13, 18, 0))
Token(type=ASSIGN, value='=', position=(13, 22, 0))
Token(type=INTEGER_LITERAL, value='10', position=(13, 23, 0))
Token(type=COMMA, value=',', position=(13, 25, 0))
Token(type=SYMBOL, value='arg2', position=(13, 27, 0))
Token(type=ASSIGN, value='=', position=(13, 31, 0))
Token(type=STRING_LITERAL, value='hello', position=(13, 32, 0))
Token(type=COMMA, value=',', position=(13, 39, 0))
Token(type=SYMBOL, value='arg3', position=(13, 41, 0))
Token(type=ASSIGN, value='=', position=(13, 45, 0))
Token(type=TRUE, value='true', position=(13, 46, 0))
Token(type=FUNCTION_CALL_END, value=')', position=(13, 50, 0))
Token(type=SYMBOL, value='mixedArgs', position=(14, 1, 0))
Token(type=ASSIGN, value='=', position=(14, 11, 0))
Token(type=SYMBOL, value='func', position=(14, 13, 0))
Token(type=FUNCTION_CALL_START, value='(', position=(14, 17, 0))
Token(type=INTEGER_LITERAL, value='5', position=(14, 18, 0))
Token(type=COMMA, value=',', position=(14, 19, 0))
Token(type=SYMBOL, value='arg1', position=(14, 21, 0))
Token(type=ASSIGN, value='=', position=(14, 25, 0))
Token(type=STRING_LITERAL, value='value', position=(14, 26, 0))
Token(type=COMMA, value=',', position=(14, 33, 0))
Token(type=INTEGER_LITERAL, value='10', position=(14, 35, 0))
Token(type=COMMA, value=',', position=(14, 37, 0))
Token(type=SYMBOL, value='arg2', position=(14, 39, 0))
Token(type=ASSIGN, value='=', position=(14, 43, 0))
Token(type=STRING_LITERAL, value='another', position=(14, 44, 0))
Token(type=FUNCTION_CALL_END, value=')', position=(14, 53, 0))
Token(type=SYMBOL, value='callOfCallOfCall', position=(16, 1, 0))
Token(type=ASSIGN, value='=', position=(16, 18, 0))
Token(type=SYMBOL, value='func1', position=(16, 20, 0))
Token(type=FUNCTION_CALL_START, value='(', position=(16, 25, 0))
Token(type=FUNCTION_CALL_END, value=')', position=(16, 26, 0))
Token(type=PARENTHESES_START, value='(', position=(16, 27, 0))
Token(type=SYMBOL, value='func2', position=(16, 28, 0))
Token(type=FUNCTION_CALL_START, value='(', position=(16, 33, 0))
Token(type=FUNCTION_CALL_END, value=')', position=(16, 34, 0))
Token(type=PARENTHESES_END, value=')', position=(16, 35, 0))
Token(type=FUNCTION_CALL_START, value='(', position=(16, 36, 0))
Token(type=SYMBOL, value='func3', position=(16, 37, 0))
Token(type=FUNCTION_CALL_START, value='(', position=(16, 42, 0))
Token(type=FUNCTION_CALL_END, value=')', position=(16, 43, 0))
Token(type=PARENTHESES_START, value='(', position=(16, 44, 0))
Token(type=INTEGER_LITERAL, value='100', position=(16, 45, 0))
Token(type=PARENTHESES_END, value=')', position=(16, 48, 0))
Token(type=FUNCTION_CALL_END, value=')', position=(16, 49, 0))
Token(type=EOF, value='', position=(142, 1, 0))
*)
