myList : List[Int] = [1, 2, 3]
myMap : Map[String, Int] = { a = 1, b = 2, c = 3 }
myTree : Tree[String, Int] = { a 1, b 2, c 3 }

(*
Token(type=SYMBOL, value="myList", position=(1, 1, 0))
Token(type=COLON, value=":", position=(1, 8, 0))
Token(type=SYMBOL, value="List", position=(1, 10, 0))
Token(type=INDEXING_START, value="[", position=(1, 14, 0))
Token(type=SYMBOL, value="Int", position=(1, 15, 0))
Token(type=INDEXING_END, value="]", position=(1, 18, 0))
Token(type=ASSIGN, value="=", position=(1, 20, 0))
Token(type=LIST_START, value="[", position=(1, 22, 0))
Token(type=INTEGER_LITERAL, value="1", position=(1, 23, 0))
Token(type=COMMA, value=",", position=(1, 24, 0))
Token(type=INTEGER_LITERAL, value="2", position=(1, 26, 0))
Token(type=COMMA, value=",", position=(1, 27, 0))
Token(type=INTEGER_LITERAL, value="3", position=(1, 29, 0))
Token(type=LIST_END, value="]", position=(1, 30, 0))
Token(type=SYMBOL, value="myMap", position=(2, 1, 0))
Token(type=COLON, value=":", position=(2, 7, 0))
Token(type=SYMBOL, value="Map", position=(2, 9, 0))
Token(type=INDEXING_START, value="[", position=(2, 12, 0))
Token(type=SYMBOL, value="String", position=(2, 13, 0))
Token(type=COMMA, value=",", position=(2, 19, 0))
Token(type=SYMBOL, value="Int", position=(2, 21, 0))
Token(type=INDEXING_END, value="]", position=(2, 24, 0))
Token(type=ASSIGN, value="=", position=(2, 26, 0))
Token(type=OBJECT_START, value="{", position=(2, 28, 0))
Token(type=SYMBOL, value="a", position=(2, 30, 0))
Token(type=ASSIGN, value="=", position=(2, 32, 0))
Token(type=INTEGER_LITERAL, value="1", position=(2, 34, 0))
Token(type=COMMA, value=",", position=(2, 35, 0))
Token(type=SYMBOL, value="b", position=(2, 37, 0))
Token(type=ASSIGN, value="=", position=(2, 39, 0))
Token(type=INTEGER_LITERAL, value="2", position=(2, 41, 0))
Token(type=COMMA, value=",", position=(2, 42, 0))
Token(type=SYMBOL, value="c", position=(2, 44, 0))
Token(type=ASSIGN, value="=", position=(2, 46, 0))
Token(type=INTEGER_LITERAL, value="3", position=(2, 48, 0))
Token(type=OBJECT_END, value="}", position=(2, 50, 0))
Token(type=SYMBOL, value="myTree", position=(3, 1, 0))
Token(type=COLON, value=":", position=(3, 8, 0))
Token(type=SYMBOL, value="Tree", position=(3, 10, 0))
Token(type=INDEXING_START, value="[", position=(3, 14, 0))
Token(type=SYMBOL, value="String", position=(3, 15, 0))
Token(type=COMMA, value=",", position=(3, 21, 0))
Token(type=SYMBOL, value="Int", position=(3, 23, 0))
Token(type=INDEXING_END, value="]", position=(3, 26, 0))
Token(type=ASSIGN, value="=", position=(3, 28, 0))
Token(type=OBJECT_START, value="{", position=(3, 30, 0))
Token(type=SYMBOL, value="a", position=(3, 32, 0))
Token(type=INTEGER_LITERAL, value="1", position=(3, 34, 0))
Token(type=COMMA, value=",", position=(3, 35, 0))
Token(type=SYMBOL, value="b", position=(3, 37, 0))
Token(type=INTEGER_LITERAL, value="2", position=(3, 39, 0))
Token(type=COMMA, value=",", position=(3, 40, 0))
Token(type=SYMBOL, value="c", position=(3, 42, 0))
Token(type=INTEGER_LITERAL, value="3", position=(3, 44, 0))
Token(type=OBJECT_END, value="}", position=(3, 46, 0))
Token(type=EOF, value="", position=(62, 3, 2))
*)