myValue = if conditionValue then valueIfTrue else valueIfFalse
nestedIf = if cond1 then if ifcond2 then thenval2 else val3 else elseval4

(*
Token(type=SYMBOL, value='myValue', position=(1, 1, 0))
Token(type=ASSIGN, value='=', position=(1, 9, 0))
Token(type=IF, value='if', position=(1, 11, 0))
Token(type=SYMBOL, value='conditionValue', position=(1, 14, 0))
Token(type=THEN, value='then', position=(1, 29, 0))
Token(type=SYMBOL, value='valueIfTrue', position=(1, 34, 0))
Token(type=ELSE, value='else', position=(1, 46, 0))
Token(type=SYMBOL, value='valueIfFalse', position=(1, 51, 0))
Token(type=SYMBOL, value='nestedIf', position=(2, 1, 0))
Token(type=ASSIGN, value='=', position=(2, 10, 0))
Token(type=IF, value='if', position=(2, 12, 0))
Token(type=SYMBOL, value='cond1', position=(2, 15, 0))
Token(type=THEN, value='then', position=(2, 21, 0))
Token(type=IF, value='if', position=(2, 26, 0))
Token(type=SYMBOL, value='ifcond2', position=(2, 29, 0))
Token(type=THEN, value='then', position=(2, 37, 0))
Token(type=SYMBOL, value='thenval2', position=(2, 42, 0))
Token(type=ELSE, value='else', position=(2, 51, 0))
Token(type=SYMBOL, value='val3', position=(2, 56, 0))
Token(type=ELSE, value='else', position=(2, 61, 0))
Token(type=SYMBOL, value='elseval4', position=(2, 66, 0))
Token(type=EOF, value='', position=(28, 1, 0))
*)
