intLiteralIndex = arr[0]
stringLiteralIndex = map["key"]

multipleIndices = matrix[1][2]

sliceAccess = arr[1:4]
sliceAccessNoStart = arr[:3]
sliceAccessNoEnd = arr[2:]
fullSliceAccess = arr[:]
nestedSliceAccess = matrix[0:2][1:3]

(*
Token(type=SYMBOL, value="intLiteralIndex", position=(1, 1, 0))
Token(type=ASSIGN, value="=", position=(1, 17, 0))
Token(type=SYMBOL, value="arr", position=(1, 19, 0))
Token(type=INDEXING_START, value="[", position=(1, 22, 0))
Token(type=INTEGER_LITERAL, value="0", position=(1, 23, 0))
Token(type=INDEXING_END, value="]", position=(1, 24, 0))
Token(type=SYMBOL, value="stringLiteralIndex", position=(2, 1, 0))
Token(type=ASSIGN, value="=", position=(2, 20, 0))
Token(type=SYMBOL, value="map", position=(2, 22, 0))
Token(type=INDEXING_START, value="[", position=(2, 25, 0))
Token(type=STRING_LITERAL, value="key", position=(2, 26, 0))
Token(type=INDEXING_END, value="]", position=(2, 31, 0))
Token(type=SYMBOL, value="multipleIndices", position=(4, 1, 0))
Token(type=ASSIGN, value="=", position=(4, 17, 0))
Token(type=SYMBOL, value="matrix", position=(4, 19, 0))
Token(type=INDEXING_START, value="[", position=(4, 25, 0))
Token(type=INTEGER_LITERAL, value="1", position=(4, 26, 0))
Token(type=INDEXING_END, value="]", position=(4, 27, 0))
Token(type=LIST_START, value="[", position=(4, 28, 0))
Token(type=INTEGER_LITERAL, value="2", position=(4, 29, 0))
Token(type=LIST_END, value="]", position=(4, 30, 0))
Token(type=SYMBOL, value="sliceAccess", position=(6, 1, 0))
Token(type=ASSIGN, value="=", position=(6, 13, 0))
Token(type=SYMBOL, value="arr", position=(6, 15, 0))
Token(type=INDEXING_START, value="[", position=(6, 18, 0))
Token(type=INTEGER_LITERAL, value="1", position=(6, 19, 0))
Token(type=COLON, value=":", position=(6, 20, 0))
Token(type=INTEGER_LITERAL, value="4", position=(6, 21, 0))
Token(type=INDEXING_END, value="]", position=(6, 22, 0))
Token(type=SYMBOL, value="sliceAccessNoStart", position=(7, 1, 0))
Token(type=ASSIGN, value="=", position=(7, 20, 0))
Token(type=SYMBOL, value="arr", position=(7, 22, 0))
Token(type=INDEXING_START, value="[", position=(7, 25, 0))
Token(type=COLON, value=":", position=(7, 26, 0))
Token(type=INTEGER_LITERAL, value="3", position=(7, 27, 0))
Token(type=INDEXING_END, value="]", position=(7, 28, 0))
Token(type=SYMBOL, value="sliceAccessNoEnd", position=(8, 1, 0))
Token(type=ASSIGN, value="=", position=(8, 18, 0))
Token(type=SYMBOL, value="arr", position=(8, 20, 0))
Token(type=INDEXING_START, value="[", position=(8, 23, 0))
Token(type=INTEGER_LITERAL, value="2", position=(8, 24, 0))
Token(type=COLON, value=":", position=(8, 25, 0))
Token(type=INDEXING_END, value="]", position=(8, 26, 0))
Token(type=SYMBOL, value="fullSliceAccess", position=(9, 1, 0))
Token(type=ASSIGN, value="=", position=(9, 17, 0))
Token(type=SYMBOL, value="arr", position=(9, 19, 0))
Token(type=INDEXING_START, value="[", position=(9, 22, 0))
Token(type=COLON, value=":", position=(9, 23, 0))
Token(type=INDEXING_END, value="]", position=(9, 24, 0))
Token(type=SYMBOL, value="nestedSliceAccess", position=(10, 1, 0))
Token(type=ASSIGN, value="=", position=(10, 19, 0))
Token(type=SYMBOL, value="matrix", position=(10, 21, 0))
Token(type=INDEXING_START, value="[", position=(10, 27, 0))
Token(type=INTEGER_LITERAL, value="0", position=(10, 28, 0))
Token(type=COLON, value=":", position=(10, 29, 0))
Token(type=INTEGER_LITERAL, value="2", position=(10, 30, 0))
Token(type=INDEXING_END, value="]", position=(10, 31, 0))
Token(type=LIST_START, value="[", position=(10, 32, 0))
Token(type=INTEGER_LITERAL, value="1", position=(10, 33, 0))
Token(type=COLON, value=":", position=(10, 34, 0))
Token(type=INTEGER_LITERAL, value="3", position=(10, 35, 0))
Token(type=LIST_END, value="]", position=(10, 36, 0))
Token(type=SYMBOL, value="expressionSlice", position=(100, 1, 0))
Token(type=ASSIGN, value="=", position=(100, 17, 0))
Token(type=SYMBOL, value="arr", position=(100, 19, 0))
Token(type=INDEXING_START, value="[", position=(100, 22, 0))
Token(type=SYMBOL, value="matrix", position=(100, 23, 0))
Token(type=INDEXING_START, value="[", position=(100, 29, 0))
Token(type=INTEGER_LITERAL, value="0", position=(100, 30, 0))
Token(type=INDEXING_END, value="]", position=(100, 31, 0))
Token(type=LIST_START, value="[", position=(100, 32, 0))
Token(type=INTEGER_LITERAL, value="0", position=(100, 33, 0))
Token(type=LIST_END, value="]", position=(100, 34, 0))
Token(type=COLON, value=":", position=(100, 36, 0))
Token(type=SYMBOL, value="matrix", position=(100, 38, 0))
Token(type=INDEXING_START, value="[", position=(100, 44, 0))
Token(type=INTEGER_LITERAL, value="1", position=(100, 45, 0))
Token(type=INDEXING_END, value="]", position=(100, 46, 0))
Token(type=LIST_START, value="[", position=(100, 47, 0))
Token(type=INTEGER_LITERAL, value="1", position=(100, 48, 0))
Token(type=LIST_END, value="]", position=(100, 49, 0))
Token(type=PLUS, value="+", position=(100, 51, 0))
Token(type=INTEGER_LITERAL, value="2", position=(100, 53, 0))
Token(type=INDEXING_END, value="]", position=(100, 54, 0))
Token(type=EOF, value="", position=(100, 55, 0))
*)

expressionSlice = arr[matrix[0][0] : matrix[1][1] + 2]