myVar = 1 + (2 * (3 + 4))

(*
Token(type=SYMBOL, value='myVar', position=(1, 1, 0))
Token(type=ASSIGN, value='=', position=(1, 7, 0))
Token(type=INTEGER_LITERAL, value='1', position=(1, 9, 0))
Token(type=PLUS, value='+', position=(1, 11, 0))
Token(type=PARENTHESES_START, value='(', position=(1, 13, 0))
Token(type=INTEGER_LITERAL, value='2', position=(1, 14, 0))
Token(type=MULTIPLY, value='*', position=(1, 16, 0))
Token(type=PARENTHESES_START, value='(', position=(1, 18, 0))
Token(type=INTEGER_LITERAL, value='3', position=(1, 19, 0))
Token(type=PLUS, value='+', position=(1, 21, 0))
Token(type=INTEGER_LITERAL, value='4', position=(1, 23, 0))
Token(type=PARENTHESES_END, value=')', position=(1, 24, 0))
Token(type=PARENTHESES_END, value=')', position=(1, 25, 0))
Token(type=EOF, value='', position=(19, 1, 0))
*)
