intValue : ( Int ) = 5
intTupleValue : (Int,Int,Int) = (1, 2, 3)

listMapAndSetTuple : ( List[String], Map[String, Int], Set[Int] ) = (
    ["a", "b"],
    { key1 = 1, key2 = 2 },
    {1, 2, 3}
)


simpleFunctionType : (Int) -> Int
multipleArgumentsFunctionType : (String, Int, Bool) -> String
namedArgumentsFunctionType : (name: String, age: List[Int]) -> Bool

optionalFunctionArgumentType : (name?: String, age?: Int, active?: Bool) -> Bool
variadicFunctionArgumentType : (...tags: String) -> Int

mixedNamedAndUnnamed : (String, age: Int, Bool) -> String

nestedFunctionType : (
    (f1: (Int, String) -> Bool, f2: (List[Int], Map[String, Int]) -> Set[String])
    -> Map[
        String,
        (arg1: Int, arg2: Int,) -> List[Bool],
    ],
    Null,
)

curriedFunctionType : (Int) -> (String) -> (Bool) -> (Int)

implicitUnnamedArgumentsFunctionType : (Int, String) -> Bool
implicitNamedArgumentsFunctionType : (       name: String,     age: List[Int]
    ,   ) -> Bool

(*
Token(type=SYMBOL, value="intValue", position=(1, 1, 0))
Token(type=COLON, value=":", position=(1, 10, 0))
Token(type=PARENTHESES_START, value="(", position=(1, 12, 0))
Token(type=SYMBOL, value="Int", position=(1, 14, 0))
Token(type=PARENTHESES_END, value=")", position=(1, 18, 0))
Token(type=ASSIGN, value="=", position=(1, 20, 0))
Token(type=INTEGER_LITERAL, value="5", position=(1, 22, 0))
Token(type=SYMBOL, value="intTupleValue", position=(2, 1, 0))
Token(type=COLON, value=":", position=(2, 15, 0))
Token(type=PARENTHESES_START, value="(", position=(2, 17, 0))
Token(type=SYMBOL, value="Int", position=(2, 18, 0))
Token(type=COMMA, value=",", position=(2, 21, 0))
Token(type=SYMBOL, value="Int", position=(2, 22, 0))
Token(type=COMMA, value=",", position=(2, 25, 0))
Token(type=SYMBOL, value="Int", position=(2, 26, 0))
Token(type=PARENTHESES_END, value=")", position=(2, 29, 0))
Token(type=ASSIGN, value="=", position=(2, 31, 0))
Token(type=PARENTHESES_START, value="(", position=(2, 33, 0))
Token(type=INTEGER_LITERAL, value="1", position=(2, 34, 0))
Token(type=COMMA, value=",", position=(2, 35, 0))
Token(type=INTEGER_LITERAL, value="2", position=(2, 37, 0))
Token(type=COMMA, value=",", position=(2, 38, 0))
Token(type=INTEGER_LITERAL, value="3", position=(2, 40, 0))
Token(type=PARENTHESES_END, value=")", position=(2, 41, 0))
Token(type=SYMBOL, value="listMapAndSetTuple", position=(4, 1, 0))
Token(type=COLON, value=":", position=(4, 20, 0))
Token(type=PARENTHESES_START, value="(", position=(4, 22, 0))
Token(type=SYMBOL, value="List", position=(4, 24, 0))
Token(type=INDEXING_START, value="[", position=(4, 28, 0))
Token(type=SYMBOL, value="String", position=(4, 29, 0))
Token(type=INDEXING_END, value="]", position=(4, 35, 0))
Token(type=COMMA, value=",", position=(4, 36, 0))
Token(type=SYMBOL, value="Map", position=(4, 38, 0))
Token(type=INDEXING_START, value="[", position=(4, 41, 0))
Token(type=SYMBOL, value="String", position=(4, 42, 0))
Token(type=COMMA, value=",", position=(4, 48, 0))
Token(type=SYMBOL, value="Int", position=(4, 50, 0))
Token(type=INDEXING_END, value="]", position=(4, 53, 0))
Token(type=COMMA, value=",", position=(4, 54, 0))
Token(type=SYMBOL, value="Set", position=(4, 56, 0))
Token(type=INDEXING_START, value="[", position=(4, 59, 0))
Token(type=SYMBOL, value="Int", position=(4, 60, 0))
Token(type=INDEXING_END, value="]", position=(4, 63, 0))
Token(type=PARENTHESES_END, value=")", position=(4, 65, 0))
Token(type=ASSIGN, value="=", position=(4, 67, 0))
Token(type=PARENTHESES_START, value="(", position=(4, 69, 0))
Token(type=LIST_START, value="[", position=(5, 5, 4))
Token(type=STRING_LITERAL, value="a", position=(5, 6, 4))
Token(type=COMMA, value=",", position=(5, 9, 4))
Token(type=STRING_LITERAL, value="b", position=(5, 11, 4))
Token(type=LIST_END, value="]", position=(5, 14, 4))
Token(type=COMMA, value=",", position=(5, 15, 4))
Token(type=OBJECT_START, value="{", position=(6, 5, 4))
Token(type=SYMBOL, value="key1", position=(6, 7, 4))
Token(type=ASSIGN, value="=", position=(6, 12, 4))
Token(type=INTEGER_LITERAL, value="1", position=(6, 14, 4))
Token(type=COMMA, value=",", position=(6, 15, 4))
Token(type=SYMBOL, value="key2", position=(6, 17, 4))
Token(type=ASSIGN, value="=", position=(6, 22, 4))
Token(type=INTEGER_LITERAL, value="2", position=(6, 24, 4))
Token(type=OBJECT_END, value="}", position=(6, 26, 4))
Token(type=COMMA, value=",", position=(6, 27, 4))
Token(type=OBJECT_START, value="{", position=(7, 5, 4))
Token(type=INTEGER_LITERAL, value="1", position=(7, 6, 4))
Token(type=COMMA, value=",", position=(7, 7, 4))
Token(type=INTEGER_LITERAL, value="2", position=(7, 9, 4))
Token(type=COMMA, value=",", position=(7, 10, 4))
Token(type=INTEGER_LITERAL, value="3", position=(7, 12, 4))
Token(type=OBJECT_END, value="}", position=(7, 13, 4))
Token(type=PARENTHESES_END, value=")", position=(8, 1, 0))
Token(type=SYMBOL, value="simpleFunctionType", position=(11, 1, 0))
Token(type=COLON, value=":", position=(11, 20, 0))
Token(type=PARENTHESES_START, value="(", position=(11, 22, 0))
Token(type=SYMBOL, value="Int", position=(11, 23, 0))
Token(type=PARENTHESES_END, value=")", position=(11, 26, 0))
Token(type=ARROW, value="->", position=(11, 28, 0))
Token(type=SYMBOL, value="Int", position=(11, 31, 0))
Token(type=SYMBOL, value="multipleArgumentsFunctionType", position=(12, 1, 0))
Token(type=COLON, value=":", position=(12, 31, 0))
Token(type=PARENTHESES_START, value="(", position=(12, 33, 0))
Token(type=SYMBOL, value="String", position=(12, 34, 0))
Token(type=COMMA, value=",", position=(12, 40, 0))
Token(type=SYMBOL, value="Int", position=(12, 42, 0))
Token(type=COMMA, value=",", position=(12, 45, 0))
Token(type=SYMBOL, value="Bool", position=(12, 47, 0))
Token(type=PARENTHESES_END, value=")", position=(12, 51, 0))
Token(type=ARROW, value="->", position=(12, 53, 0))
Token(type=SYMBOL, value="String", position=(12, 56, 0))
Token(type=SYMBOL, value="namedArgumentsFunctionType", position=(13, 1, 0))
Token(type=COLON, value=":", position=(13, 28, 0))
Token(type=PARENTHESES_START, value="(", position=(13, 30, 0))
Token(type=SYMBOL, value="name", position=(13, 31, 0))
Token(type=COLON, value=":", position=(13, 35, 0))
Token(type=SYMBOL, value="String", position=(13, 37, 0))
Token(type=COMMA, value=",", position=(13, 43, 0))
Token(type=SYMBOL, value="age", position=(13, 45, 0))
Token(type=COLON, value=":", position=(13, 48, 0))
Token(type=SYMBOL, value="List", position=(13, 50, 0))
Token(type=INDEXING_START, value="[", position=(13, 54, 0))
Token(type=SYMBOL, value="Int", position=(13, 55, 0))
Token(type=INDEXING_END, value="]", position=(13, 58, 0))
Token(type=PARENTHESES_END, value=")", position=(13, 59, 0))
Token(type=ARROW, value="->", position=(13, 61, 0))
Token(type=SYMBOL, value="Bool", position=(13, 64, 0))
Token(type=SYMBOL, value="optionalFunctionArgumentType", position=(15, 1, 0))
Token(type=COLON, value=":", position=(15, 30, 0))
Token(type=PARENTHESES_START, value="(", position=(15, 32, 0))
Token(type=SYMBOL, value="name", position=(15, 33, 0))
Token(type=QUESTION, value="?", position=(15, 37, 0))
Token(type=COLON, value=":", position=(15, 38, 0))
Token(type=SYMBOL, value="String", position=(15, 40, 0))
Token(type=COMMA, value=",", position=(15, 46, 0))
Token(type=SYMBOL, value="age", position=(15, 48, 0))
Token(type=QUESTION, value="?", position=(15, 51, 0))
Token(type=COLON, value=":", position=(15, 52, 0))
Token(type=SYMBOL, value="Int", position=(15, 54, 0))
Token(type=COMMA, value=",", position=(15, 57, 0))
Token(type=SYMBOL, value="active", position=(15, 59, 0))
Token(type=QUESTION, value="?", position=(15, 65, 0))
Token(type=COLON, value=":", position=(15, 66, 0))
Token(type=SYMBOL, value="Bool", position=(15, 68, 0))
Token(type=PARENTHESES_END, value=")", position=(15, 72, 0))
Token(type=ARROW, value="->", position=(15, 74, 0))
Token(type=SYMBOL, value="Bool", position=(15, 77, 0))
Token(type=SYMBOL, value="variadicFunctionArgumentType", position=(16, 1, 0))
Token(type=COLON, value=":", position=(16, 30, 0))
Token(type=PARENTHESES_START, value="(", position=(16, 32, 0))
Token(type=ELLIPSIS, value="...", position=(16, 33, 0))
Token(type=SYMBOL, value="tags", position=(16, 36, 0))
Token(type=COLON, value=":", position=(16, 40, 0))
Token(type=SYMBOL, value="String", position=(16, 42, 0))
Token(type=PARENTHESES_END, value=")", position=(16, 48, 0))
Token(type=ARROW, value="->", position=(16, 50, 0))
Token(type=SYMBOL, value="Int", position=(16, 53, 0))
Token(type=SYMBOL, value="mixedNamedAndUnnamed", position=(18, 1, 0))
Token(type=COLON, value=":", position=(18, 22, 0))
Token(type=PARENTHESES_START, value="(", position=(18, 24, 0))
Token(type=SYMBOL, value="String", position=(18, 25, 0))
Token(type=COMMA, value=",", position=(18, 31, 0))
Token(type=SYMBOL, value="age", position=(18, 33, 0))
Token(type=COLON, value=":", position=(18, 36, 0))
Token(type=SYMBOL, value="Int", position=(18, 38, 0))
Token(type=COMMA, value=",", position=(18, 41, 0))
Token(type=SYMBOL, value="Bool", position=(18, 43, 0))
Token(type=PARENTHESES_END, value=")", position=(18, 47, 0))
Token(type=ARROW, value="->", position=(18, 49, 0))
Token(type=SYMBOL, value="String", position=(18, 52, 0))
Token(type=SYMBOL, value="nestedFunctionType", position=(20, 1, 0))
Token(type=COLON, value=":", position=(20, 20, 0))
Token(type=PARENTHESES_START, value="(", position=(20, 22, 0))
Token(type=PARENTHESES_START, value="(", position=(21, 5, 4))
Token(type=SYMBOL, value="f1", position=(21, 6, 4))
Token(type=COLON, value=":", position=(21, 8, 4))
Token(type=PARENTHESES_START, value="(", position=(21, 10, 4))
Token(type=SYMBOL, value="Int", position=(21, 11, 4))
Token(type=COMMA, value=",", position=(21, 14, 4))
Token(type=SYMBOL, value="String", position=(21, 16, 4))
Token(type=PARENTHESES_END, value=")", position=(21, 22, 4))
Token(type=ARROW, value="->", position=(21, 24, 4))
Token(type=SYMBOL, value="Bool", position=(21, 27, 4))
Token(type=COMMA, value=",", position=(21, 31, 4))
Token(type=SYMBOL, value="f2", position=(21, 33, 4))
Token(type=COLON, value=":", position=(21, 35, 4))
Token(type=PARENTHESES_START, value="(", position=(21, 37, 4))
Token(type=SYMBOL, value="List", position=(21, 38, 4))
Token(type=INDEXING_START, value="[", position=(21, 42, 4))
Token(type=SYMBOL, value="Int", position=(21, 43, 4))
Token(type=INDEXING_END, value="]", position=(21, 46, 4))
Token(type=COMMA, value=",", position=(21, 47, 4))
Token(type=SYMBOL, value="Map", position=(21, 49, 4))
Token(type=INDEXING_START, value="[", position=(21, 52, 4))
Token(type=SYMBOL, value="String", position=(21, 53, 4))
Token(type=COMMA, value=",", position=(21, 59, 4))
Token(type=SYMBOL, value="Int", position=(21, 61, 4))
Token(type=INDEXING_END, value="]", position=(21, 64, 4))
Token(type=PARENTHESES_END, value=")", position=(21, 65, 4))
Token(type=ARROW, value="->", position=(21, 67, 4))
Token(type=SYMBOL, value="Set", position=(21, 70, 4))
Token(type=INDEXING_START, value="[", position=(21, 73, 4))
Token(type=SYMBOL, value="String", position=(21, 74, 4))
Token(type=INDEXING_END, value="]", position=(21, 80, 4))
Token(type=PARENTHESES_END, value=")", position=(21, 81, 4))
Token(type=ARROW, value="->", position=(22, 5, 4))
Token(type=SYMBOL, value="Map", position=(22, 8, 4))
Token(type=INDEXING_START, value="[", position=(22, 11, 4))
Token(type=SYMBOL, value="String", position=(23, 9, 8))
Token(type=COMMA, value=",", position=(23, 15, 8))
Token(type=PARENTHESES_START, value="(", position=(24, 9, 8))
Token(type=SYMBOL, value="arg1", position=(24, 10, 8))
Token(type=COLON, value=":", position=(24, 14, 8))
Token(type=SYMBOL, value="Int", position=(24, 16, 8))
Token(type=COMMA, value=",", position=(24, 19, 8))
Token(type=SYMBOL, value="arg2", position=(24, 21, 8))
Token(type=COLON, value=":", position=(24, 25, 8))
Token(type=SYMBOL, value="Int", position=(24, 27, 8))
Token(type=COMMA, value=",", position=(24, 30, 8))
Token(type=PARENTHESES_END, value=")", position=(24, 31, 8))
Token(type=ARROW, value="->", position=(24, 33, 8))
Token(type=SYMBOL, value="List", position=(24, 36, 8))
Token(type=INDEXING_START, value="[", position=(24, 40, 8))
Token(type=SYMBOL, value="Bool", position=(24, 41, 8))
Token(type=INDEXING_END, value="]", position=(24, 45, 8))
Token(type=COMMA, value=",", position=(24, 46, 8))
Token(type=INDEXING_END, value="]", position=(25, 5, 4))
Token(type=COMMA, value=",", position=(25, 6, 4))
Token(type=SYMBOL, value="Null", position=(26, 5, 4))
Token(type=COMMA, value=",", position=(26, 9, 4))
Token(type=PARENTHESES_END, value=")", position=(27, 1, 0))
Token(type=SYMBOL, value="curriedFunctionType", position=(29, 1, 0))
Token(type=COLON, value=":", position=(29, 21, 0))
Token(type=PARENTHESES_START, value="(", position=(29, 23, 0))
Token(type=SYMBOL, value="Int", position=(29, 24, 0))
Token(type=PARENTHESES_END, value=")", position=(29, 27, 0))
Token(type=ARROW, value="->", position=(29, 29, 0))
Token(type=PARENTHESES_START, value="(", position=(29, 32, 0))
Token(type=SYMBOL, value="String", position=(29, 33, 0))
Token(type=PARENTHESES_END, value=")", position=(29, 39, 0))
Token(type=ARROW, value="->", position=(29, 41, 0))
Token(type=PARENTHESES_START, value="(", position=(29, 44, 0))
Token(type=SYMBOL, value="Bool", position=(29, 45, 0))
Token(type=PARENTHESES_END, value=")", position=(29, 49, 0))
Token(type=ARROW, value="->", position=(29, 51, 0))
Token(type=PARENTHESES_START, value="(", position=(29, 54, 0))
Token(type=SYMBOL, value="Int", position=(29, 55, 0))
Token(type=PARENTHESES_END, value=")", position=(29, 58, 0))
Token(type=SYMBOL, value="implicitUnnamedArgumentsFunctionType", position=(31, 1, 0))
Token(type=COLON, value=":", position=(31, 38, 0))
Token(type=PARENTHESES_START, value="(", position=(31, 40, 0))
Token(type=SYMBOL, value="Int", position=(31, 41, 0))
Token(type=COMMA, value=",", position=(31, 44, 0))
Token(type=SYMBOL, value="String", position=(31, 46, 0))
Token(type=PARENTHESES_END, value=")", position=(31, 52, 0))
Token(type=ARROW, value="->", position=(31, 54, 0))
Token(type=SYMBOL, value="Bool", position=(31, 57, 0))
Token(type=SYMBOL, value="implicitNamedArgumentsFunctionType", position=(32, 1, 0))
Token(type=COLON, value=":", position=(32, 36, 0))
Token(type=PARENTHESES_START, value="(", position=(32, 38, 0))
Token(type=SYMBOL, value="name", position=(32, 46, 0))
Token(type=COLON, value=":", position=(32, 50, 0))
Token(type=SYMBOL, value="String", position=(32, 52, 0))
Token(type=COMMA, value=",", position=(32, 58, 0))
Token(type=SYMBOL, value="age", position=(32, 64, 0))
Token(type=COLON, value=":", position=(32, 67, 0))
Token(type=SYMBOL, value="List", position=(32, 69, 0))
Token(type=INDEXING_START, value="[", position=(32, 73, 0))
Token(type=SYMBOL, value="Int", position=(32, 74, 0))
Token(type=INDEXING_END, value="]", position=(32, 77, 0))
Token(type=COMMA, value=",", position=(33, 5, 4))
Token(type=PARENTHESES_END, value=")", position=(33, 9, 4))
Token(type=ARROW, value="->", position=(33, 11, 4))
Token(type=SYMBOL, value="Bool", position=(33, 14, 4))
Token(type=EOF, value="", position=(288, 3, 2))
*)