singleElementTuple = (element,)
multiElementTuple = (element1, element2, element3)
multiElementTupleWithTrailingComma = (
    element1, 
    element2, 
    element3,
)
nestedTuples = ((element1, element2), (element3, element4), (element5,))

(*
Token(type=SYMBOL, value='singleElementTuple', position=(1, 1, 0))
Token(type=ASSIGN, value='=', position=(1, 20, 0))
Token(type=PARENTHESES_START, value='(', position=(1, 22, 0))
Token(type=SYMBOL, value='element', position=(1, 23, 0))
Token(type=COMMA, value=',', position=(1, 30, 0))
Token(type=PARENTHESES_END, value=')', position=(1, 31, 0))
Token(type=SYMBOL, value='multiElementTuple', position=(2, 1, 0))
Token(type=ASSIGN, value='=', position=(2, 19, 0))
Token(type=PARENTHESES_START, value='(', position=(2, 21, 0))
Token(type=SYMBOL, value='element1', position=(2, 22, 0))
Token(type=COMMA, value=',', position=(2, 30, 0))
Token(type=SYMBOL, value='element2', position=(2, 32, 0))
Token(type=COMMA, value=',', position=(2, 40, 0))
Token(type=SYMBOL, value='element3', position=(2, 42, 0))
Token(type=PARENTHESES_END, value=')', position=(2, 50, 0))
Token(type=SYMBOL, value='multiElementTupleWithTrailingComma', position=(3, 1, 0))
Token(type=ASSIGN, value='=', position=(3, 36, 0))
Token(type=PARENTHESES_START, value='(', position=(3, 38, 0))
Token(type=SYMBOL, value='element1', position=(4, 5, 4))
Token(type=COMMA, value=',', position=(4, 13, 4))
Token(type=SYMBOL, value='element2', position=(5, 5, 4))
Token(type=COMMA, value=',', position=(5, 13, 4))
Token(type=SYMBOL, value='element3', position=(6, 5, 4))
Token(type=COMMA, value=',', position=(6, 13, 4))
Token(type=PARENTHESES_END, value=')', position=(7, 1, 0))
Token(type=SYMBOL, value='nestedTuples', position=(8, 1, 0))
Token(type=ASSIGN, value='=', position=(8, 14, 0))
Token(type=PARENTHESES_START, value='(', position=(8, 16, 0))
Token(type=PARENTHESES_START, value='(', position=(8, 17, 0))
Token(type=SYMBOL, value='element1', position=(8, 18, 0))
Token(type=COMMA, value=',', position=(8, 26, 0))
Token(type=SYMBOL, value='element2', position=(8, 28, 0))
Token(type=PARENTHESES_END, value=')', position=(8, 36, 0))
Token(type=COMMA, value=',', position=(8, 37, 0))
Token(type=PARENTHESES_START, value='(', position=(8, 39, 0))
Token(type=SYMBOL, value='element3', position=(8, 40, 0))
Token(type=COMMA, value=',', position=(8, 48, 0))
Token(type=SYMBOL, value='element4', position=(8, 50, 0))
Token(type=PARENTHESES_END, value=')', position=(8, 58, 0))
Token(type=COMMA, value=',', position=(8, 59, 0))
Token(type=PARENTHESES_START, value='(', position=(8, 61, 0))
Token(type=SYMBOL, value='element5', position=(8, 62, 0))
Token(type=COMMA, value=',', position=(8, 70, 0))
Token(type=PARENTHESES_END, value=')', position=(8, 71, 0))
Token(type=PARENTHESES_END, value=')', position=(8, 72, 0))
Token(type=EOF, value='', position=(58, 1, 0))
*)
