myList : List[String]
myList = [ "a", "b", "c" ]

myMap : Map[String, Int]
myMap = { a = 1, ["b"] = 2, c = 3 }

(*
Token(type=SYMBOL, value="myList", position=(1, 1, 0))
Token(type=COLON, value=":", position=(1, 8, 0))
Token(type=SYMBOL, value="List", position=(1, 10, 0))
Token(type=INDEXING_START, value="[", position=(1, 14, 0))
Token(type=SYMBOL, value="String", position=(1, 15, 0))
Token(type=INDEXING_END, value="]", position=(1, 21, 0))
Token(type=SYMBOL, value="myList", position=(2, 1, 0))
Token(type=ASSIGN, value="=", position=(2, 8, 0))
Token(type=LIST_START, value="[", position=(2, 10, 0))
Token(type=STRING_LITERAL, value="a", position=(2, 12, 0))
Token(type=COMMA, value=",", position=(2, 15, 0))
Token(type=STRING_LITERAL, value="b", position=(2, 17, 0))
Token(type=COMMA, value=",", position=(2, 20, 0))
Token(type=STRING_LITERAL, value="c", position=(2, 22, 0))
Token(type=LIST_END, value="]", position=(2, 26, 0))
Token(type=SYMBOL, value="myMap", position=(4, 1, 0))
Token(type=COLON, value=":", position=(4, 7, 0))
Token(type=SYMBOL, value="Map", position=(4, 9, 0))
Token(type=INDEXING_START, value="[", position=(4, 12, 0))
Token(type=SYMBOL, value="String", position=(4, 13, 0))
Token(type=COMMA, value=",", position=(4, 19, 0))
Token(type=SYMBOL, value="Int", position=(4, 21, 0))
Token(type=INDEXING_END, value="]", position=(4, 24, 0))
Token(type=SYMBOL, value="myMap", position=(5, 1, 0))
Token(type=ASSIGN, value="=", position=(5, 7, 0))
Token(type=OBJECT_START, value="{", position=(5, 9, 0))
Token(type=SYMBOL, value="a", position=(5, 11, 0))
Token(type=ASSIGN, value="=", position=(5, 13, 0))
Token(type=INTEGER_LITERAL, value="1", position=(5, 15, 0))
Token(type=COMMA, value=",", position=(5, 16, 0))
Token(type=LIST_START, value="[", position=(5, 18, 0))
Token(type=STRING_LITERAL, value="b", position=(5, 19, 0))
Token(type=LIST_END, value="]", position=(5, 22, 0))
Token(type=ASSIGN, value="=", position=(5, 24, 0))
Token(type=INTEGER_LITERAL, value="2", position=(5, 26, 0))
Token(type=COMMA, value=",", position=(5, 27, 0))
Token(type=SYMBOL, value="c", position=(5, 29, 0))
Token(type=ASSIGN, value="=", position=(5, 31, 0))
Token(type=INTEGER_LITERAL, value="3", position=(5, 33, 0))
Token(type=OBJECT_END, value="}", position=(5, 35, 0))
Token(type=EOF, value="", position=(50, 1, 0))
*)
