a : List[Int]
    | Map[String, Int]
    | Set[Int] = { a = 1 }

(*
Token(type=SYMBOL, value='a', position=(1, 1, 0))
Token(type=COLON, value=':', position=(1, 3, 0))
Token(type=SYMBOL, value='List', position=(1, 5, 0))
Token(type=INDEXING_START, value='[', position=(1, 9, 0))
Token(type=SYMBOL, value='Int', position=(1, 10, 0))
Token(type=INDEXING_END, value=']', position=(1, 13, 0))
Token(type=VARIANT, value='|', position=(2, 5, 4))
Token(type=SYMBOL, value='Map', position=(2, 7, 4))
Token(type=INDEXING_START, value='[', position=(2, 10, 4))
Token(type=SYMBOL, value='String', position=(2, 11, 4))
Token(type=COMMA, value=',', position=(2, 17, 4))
Token(type=SYMBOL, value='Int', position=(2, 19, 4))
Token(type=INDEXING_END, value=']', position=(2, 22, 4))
Token(type=VARIANT, value='|', position=(3, 5, 4))
Token(type=SYMBOL, value='Set', position=(3, 7, 4))
Token(type=INDEXING_START, value='[', position=(3, 10, 4))
Token(type=SYMBOL, value='Int', position=(3, 11, 4))
Token(type=INDEXING_END, value=']', position=(3, 14, 4))
Token(type=ASSIGN, value='=', position=(3, 16, 4))
Token(type=OBJECT_START, value='{', position=(3, 18, 4))
Token(type=SYMBOL, value='a', position=(3, 20, 4))
Token(type=ASSIGN, value='=', position=(3, 22, 4))
Token(type=INTEGER_LITERAL, value='1', position=(3, 24, 4))
Token(type=OBJECT_END, value='}', position=(3, 26, 4))
Token(type=EOF, value='', position=(32, 1, 0))
*)
