intLiteralIndex = arr[0]
stringLiteralIndex = map["key"]

multipleIndices = matrix[1][2]

(*
Token(type=SYMBOL, value="intLiteralIndex", position=(1, 1, 0))
Token(type=ASSIGN, value="=", position=(1, 17, 0))
Token(type=SYMBOL, value="arr", position=(1, 19, 0))
Token(type=INDEXING_START, value="[", position=(1, 22, 0))
Token(type=INTEGER_LITERAL, value="0", position=(1, 23, 0))
Token(type=INDEXING_END, value="]", position=(1, 24, 0))
Token(type=SYMBOL, value="stringLiteralIndex", position=(2, 1, 0))
Token(type=ASSIGN, value="=", position=(2, 20, 0))
Token(type=SYMBOL, value="map", position=(2, 22, 0))
Token(type=INDEXING_START, value="[", position=(2, 25, 0))
Token(type=STRING_LITERAL, value="key", position=(2, 26, 0))
Token(type=INDEXING_END, value="]", position=(2, 31, 0))
Token(type=SYMBOL, value="multipleIndices", position=(4, 1, 0))
Token(type=ASSIGN, value="=", position=(4, 17, 0))
Token(type=SYMBOL, value="matrix", position=(4, 19, 0))
Token(type=INDEXING_START, value="[", position=(4, 25, 0))
Token(type=INTEGER_LITERAL, value="1", position=(4, 26, 0))
Token(type=INDEXING_END, value="]", position=(4, 27, 0))
Token(type=INDEXING_START, value="[", position=(4, 28, 0))
Token(type=INTEGER_LITERAL, value="2", position=(4, 29, 0))
Token(type=INDEXING_END, value="]", position=(4, 30, 0))
Token(type=SYMBOL, value="expressionSlice", position=(53, 1, 0))
Token(type=ASSIGN, value="=", position=(53, 17, 0))
Token(type=SYMBOL, value="arr", position=(53, 19, 0))
Token(type=INDEXING_START, value="[", position=(53, 22, 0))
Token(type=SYMBOL, value="matrix", position=(53, 23, 0))
Token(type=INDEXING_START, value="[", position=(53, 29, 0))
Token(type=INTEGER_LITERAL, value="0", position=(53, 30, 0))
Token(type=INDEXING_END, value="]", position=(53, 31, 0))
Token(type=INDEXING_START, value="[", position=(53, 32, 0))
Token(type=INTEGER_LITERAL, value="0", position=(53, 33, 0))
Token(type=INDEXING_END, value="]", position=(53, 34, 0))
Token(type=COLON, value=":", position=(53, 36, 0))
Token(type=SYMBOL, value="matrix", position=(53, 38, 0))
Token(type=INDEXING_START, value="[", position=(53, 44, 0))
Token(type=INTEGER_LITERAL, value="1", position=(53, 45, 0))
Token(type=INDEXING_END, value="]", position=(53, 46, 0))
Token(type=INDEXING_START, value="[", position=(53, 47, 0))
Token(type=INTEGER_LITERAL, value="1", position=(53, 48, 0))
Token(type=INDEXING_END, value="]", position=(53, 49, 0))
Token(type=PLUS, value="+", position=(53, 51, 0))
Token(type=INTEGER_LITERAL, value="2", position=(53, 53, 0))
Token(type=INDEXING_END, value="]", position=(53, 54, 0))
Token(type=EOF, value="", position=(53, 55, 0))
*)

expressionSlice = arr[matrix[0][0] : matrix[1][1] + 2]