binaryAnd = true and false
binaryAndOr = true and false or true
binaryOrAnd = false or true and false

plusMinus = 1 + 2 - 3
minusPlus = 4 - 5 + 6
mixedArithmetic = 7 + 8 - 9 * 10 / 11 + 12 // 13 % 14 ** 15 ** 16

allOperators =
    1 * 2 + 3 - 4 / 5 == 6 != 7 < 8 <= 9 > 10 and 
    11 or 12 |> 13 |> 15 // 16 % 17 ** 18  ** 19 >= 20 or
    not not
    not notand and
    not - 22 - -23 +-+-+-24

(*
allOperators =
    ((((((((((((1 * 2) + 3) - (4 / 5)) == 6) != 7) < 8) <= 9) > 10) and 
    11) or 12) |> 13) |> ((((15 // 16) % (17 ** (18  ** 19))) >= 20) or
    ((not (not
    (not notand))) and
    (not (((- 22) - (-23)) +(-(+(-(+(-24))))))))))
*)

(*
Module(
    top_level_nodes=[
        VariableBindingStatement(
            name=Symbol(
                name="binaryAnd"
            ),
            value=BinaryOperation(
                left=Symbol(
                    name="true"
                ),
                operator="and",
                right=Symbol(
                    name="false"
                )
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="binaryAndOr"
            ),
            value=BinaryOperation(
                left=BinaryOperation(
                    left=Symbol(
                        name="true"
                    ),
                    operator="and",
                    right=Symbol(
                        name="false"
                    )
                ),
                operator="or",
                right=Symbol(
                    name="true"
                )
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="binaryOrAnd"
            ),
            value=BinaryOperation(
                left=Symbol(
                    name="false"
                ),
                operator="or",
                right=BinaryOperation(
                    left=Symbol(
                        name="true"
                    ),
                    operator="and",
                    right=Symbol(
                        name="false"
                    )
                )
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="plusMinus"
            ),
            value=BinaryOperation(
                left=BinaryOperation(
                    left=IntegerLiteral(
                        value="1"
                    ),
                    operator="+",
                    right=IntegerLiteral(
                        value="2"
                    )
                ),
                operator="-",
                right=IntegerLiteral(
                    value="3"
                )
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="minusPlus"
            ),
            value=BinaryOperation(
                left=BinaryOperation(
                    left=IntegerLiteral(
                        value="4"
                    ),
                    operator="-",
                    right=IntegerLiteral(
                        value="5"
                    )
                ),
                operator="+",
                right=IntegerLiteral(
                    value="6"
                )
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="mixedArithmetic"
            ),
            value=BinaryOperation(
                left=BinaryOperation(
                    left=BinaryOperation(
                        left=IntegerLiteral(
                            value="7"
                        ),
                        operator="+",
                        right=IntegerLiteral(
                            value="8"
                        )
                    ),
                    operator="-",
                    right=BinaryOperation(
                        left=BinaryOperation(
                            left=IntegerLiteral(
                                value="9"
                            ),
                            operator="*",
                            right=IntegerLiteral(
                                value="10"
                            )
                        ),
                        operator="/",
                        right=IntegerLiteral(
                            value="11"
                        )
                    )
                ),
                operator="+",
                right=BinaryOperation(
                    left=BinaryOperation(
                        left=IntegerLiteral(
                            value="12"
                        ),
                        operator="//",
                        right=IntegerLiteral(
                            value="13"
                        )
                    ),
                    operator="%",
                    right=BinaryOperation(
                        left=IntegerLiteral(
                            value="14"
                        ),
                        operator="**",
                        right=BinaryOperation(
                            left=IntegerLiteral(
                                value="15"
                            ),
                            operator="**",
                            right=IntegerLiteral(
                                value="16"
                            )
                        )
                    )
                )
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="allOperators"
            ),
            value=BinaryOperation(
                left=BinaryOperation(
                    left=BinaryOperation(
                        left=BinaryOperation(
                            left=BinaryOperation(
                                left=BinaryOperation(
                                    left=BinaryOperation(
                                        left=BinaryOperation(
                                            left=BinaryOperation(
                                                left=BinaryOperation(
                                                    left=BinaryOperation(
                                                        left=BinaryOperation(
                                                            left=IntegerLiteral(
                                                                value="1"
                                                            ),
                                                            operator="*",
                                                            right=IntegerLiteral(
                                                                value="2"
                                                            )
                                                        ),
                                                        operator="+",
                                                        right=IntegerLiteral(
                                                            value="3"
                                                        )
                                                    ),
                                                    operator="-",
                                                    right=BinaryOperation(
                                                        left=IntegerLiteral(
                                                            value="4"
                                                        ),
                                                        operator="/",
                                                        right=IntegerLiteral(
                                                            value="5"
                                                        )
                                                    )
                                                ),
                                                operator="==",
                                                right=IntegerLiteral(
                                                    value="6"
                                                )
                                            ),
                                            operator="!=",
                                            right=IntegerLiteral(
                                                value="7"
                                            )
                                        ),
                                        operator="<",
                                        right=IntegerLiteral(
                                            value="8"
                                        )
                                    ),
                                    operator="<=",
                                    right=IntegerLiteral(
                                        value="9"
                                    )
                                ),
                                operator=">",
                                right=IntegerLiteral(
                                    value="10"
                                )
                            ),
                            operator="and",
                            right=IntegerLiteral(
                                value="11"
                            )
                        ),
                        operator="or",
                        right=IntegerLiteral(
                            value="12"
                        )
                    ),
                    operator="|>",
                    right=IntegerLiteral(
                        value="13"
                    )
                ),
                operator="|>",
                right=BinaryOperation(
                    left=BinaryOperation(
                        left=BinaryOperation(
                            left=BinaryOperation(
                                left=IntegerLiteral(
                                    value="15"
                                ),
                                operator="//",
                                right=IntegerLiteral(
                                    value="16"
                                )
                            ),
                            operator="%",
                            right=BinaryOperation(
                                left=IntegerLiteral(
                                    value="17"
                                ),
                                operator="**",
                                right=BinaryOperation(
                                    left=IntegerLiteral(
                                        value="18"
                                    ),
                                    operator="**",
                                    right=IntegerLiteral(
                                        value="19"
                                    )
                                )
                            )
                        ),
                        operator=">=",
                        right=IntegerLiteral(
                            value="20"
                        )
                    ),
                    operator="or",
                    right=BinaryOperation(
                        left=UnaryOperation(
                            operator="not",
                            operand=UnaryOperation(
                                operator="not",
                                operand=UnaryOperation(
                                    operator="not",
                                    operand=Symbol(
                                        name="notand"
                                    )
                                )
                            )
                        ),
                        operator="and",
                        right=UnaryOperation(
                            operator="not",
                            operand=BinaryOperation(
                                left=BinaryOperation(
                                    left=UnaryOperation(
                                        operator="-",
                                        operand=IntegerLiteral(
                                            value="22"
                                        )
                                    ),
                                    operator="-",
                                    right=UnaryOperation(
                                        operator="-",
                                        operand=IntegerLiteral(
                                            value="23"
                                        )
                                    )
                                ),
                                operator="+",
                                right=UnaryOperation(
                                    operator="-",
                                    operand=UnaryOperation(
                                        operator="+",
                                        operand=UnaryOperation(
                                            operator="-",
                                            operand=UnaryOperation(
                                                operator="+",
                                                operand=UnaryOperation(
                                                    operator="-",
                                                    operand=IntegerLiteral(
                                                        value="24"
                                                    )
                                                )
                                            )
                                        )
                                    )
                                )
                            )
                        )
                    )
                )
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="plusMinusPlus"
            ),
            value=BinaryOperation(
                left=BinaryOperation(
                    left=BinaryOperation(
                        left=IntegerLiteral(
                            value="1"
                        ),
                        operator="+",
                        right=IntegerLiteral(
                            value="2"
                        )
                    ),
                    operator="-",
                    right=IntegerLiteral(
                        value="3"
                    )
                ),
                operator="+",
                right=IntegerLiteral(
                    value="4"
                )
            )
        )
    ]
)
*)

plusMinusPlus = 1 + 2 - 3 + 4