noArgs = func(    )
singleArg = func(42)
singleArgTrailingComma = func(
    42,
)

multipleArgs = func(1, 2, 3)
nestedFunctionCalls = outerFunc(innerFunc1(10), innerFunc2(20, 30))

methodCall = obj.method(100, "test")
chainedMethodCalls = obj.firstMethod().secondMethod(200).thirdMethod("chain")

namedArgs = func(arg1=10, arg2="hello", arg3=true)
mixedArgs = func(5, arg1="value", 10, arg2="another")

callOfCallOfCall = func1()(func2())(func3()(100))

(*
Module(
    top_level_nodes=[
        VariableBindingStatement(
            name=Symbol(
                name="noArgs"
            ),
            value=FunctionCall(
                function=Symbol(
                    name="func"
                ),
                arguments=[

                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="singleArg"
            ),
            value=FunctionCall(
                function=Symbol(
                    name="func"
                ),
                arguments=[
                    FunctionCallArgument(
                        value=IntegerLiteral(
                            value="42"
                        )
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="singleArgTrailingComma"
            ),
            value=FunctionCall(
                function=Symbol(
                    name="func"
                ),
                arguments=[
                    FunctionCallArgument(
                        value=IntegerLiteral(
                            value="42"
                        )
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="multipleArgs"
            ),
            value=FunctionCall(
                function=Symbol(
                    name="func"
                ),
                arguments=[
                    FunctionCallArgument(
                        value=IntegerLiteral(
                            value="1"
                        )
                    ),
                    FunctionCallArgument(
                        value=IntegerLiteral(
                            value="2"
                        )
                    ),
                    FunctionCallArgument(
                        value=IntegerLiteral(
                            value="3"
                        )
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="nestedFunctionCalls"
            ),
            value=FunctionCall(
                function=Symbol(
                    name="outerFunc"
                ),
                arguments=[
                    FunctionCallArgument(
                        value=FunctionCall(
                            function=Symbol(
                                name="innerFunc1"
                            ),
                            arguments=[
                                FunctionCallArgument(
                                    value=IntegerLiteral(
                                        value="10"
                                    )
                                )
                            ]
                        )
                    ),
                    FunctionCallArgument(
                        value=FunctionCall(
                            function=Symbol(
                                name="innerFunc2"
                            ),
                            arguments=[
                                FunctionCallArgument(
                                    value=IntegerLiteral(
                                        value="20"
                                    )
                                ),
                                FunctionCallArgument(
                                    value=IntegerLiteral(
                                        value="30"
                                    )
                                )
                            ]
                        )
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="methodCall"
            ),
            value=FunctionCall(
                function=AttributeAccess(
                    object=Symbol(
                        name="obj"
                    ),
                    attribute=Symbol(
                        name="method"
                    )
                ),
                arguments=[
                    FunctionCallArgument(
                        value=IntegerLiteral(
                            value="100"
                        )
                    ),
                    FunctionCallArgument(
                        value=StringLiteral(
                            value="test"
                        )
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="chainedMethodCalls"
            ),
            value=FunctionCall(
                function=AttributeAccess(
                    object=FunctionCall(
                        function=AttributeAccess(
                            object=FunctionCall(
                                function=AttributeAccess(
                                    object=Symbol(
                                        name="obj"
                                    ),
                                    attribute=Symbol(
                                        name="firstMethod"
                                    )
                                ),
                                arguments=[

                                ]
                            ),
                            attribute=Symbol(
                                name="secondMethod"
                            )
                        ),
                        arguments=[
                            FunctionCallArgument(
                                value=IntegerLiteral(
                                    value="200"
                                )
                            )
                        ]
                    ),
                    attribute=Symbol(
                        name="thirdMethod"
                    )
                ),
                arguments=[
                    FunctionCallArgument(
                        value=StringLiteral(
                            value="chain"
                        )
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="namedArgs"
            ),
            value=FunctionCall(
                function=Symbol(
                    name="func"
                ),
                arguments=[
                    FunctionCallArgument(
                        name=Symbol(
                            name="arg1"
                        ),
                        value=IntegerLiteral(
                            value="10"
                        )
                    ),
                    FunctionCallArgument(
                        name=Symbol(
                            name="arg2"
                        ),
                        value=StringLiteral(
                            value="hello"
                        )
                    ),
                    FunctionCallArgument(
                        name=Symbol(
                            name="arg3"
                        ),
                        value=Symbol(
                            name="true"
                        )
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="mixedArgs"
            ),
            value=FunctionCall(
                function=Symbol(
                    name="func"
                ),
                arguments=[
                    FunctionCallArgument(
                        value=IntegerLiteral(
                            value="5"
                        )
                    ),
                    FunctionCallArgument(
                        name=Symbol(
                            name="arg1"
                        ),
                        value=StringLiteral(
                            value="value"
                        )
                    ),
                    FunctionCallArgument(
                        value=IntegerLiteral(
                            value="10"
                        )
                    ),
                    FunctionCallArgument(
                        name=Symbol(
                            name="arg2"
                        ),
                        value=StringLiteral(
                            value="another"
                        )
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="callOfCallOfCall"
            ),
            value=FunctionCall(
                function=FunctionCall(
                    function=FunctionCall(
                        function=Symbol(
                            name="func1"
                        ),
                        arguments=[

                        ]
                    ),
                    arguments=[
                        FunctionCallArgument(
                            value=FunctionCall(
                                function=Symbol(
                                    name="func2"
                                ),
                                arguments=[

                                ]
                            )
                        )
                    ]
                ),
                arguments=[
                    FunctionCallArgument(
                        value=FunctionCall(
                            function=FunctionCall(
                                function=Symbol(
                                    name="func3"
                                ),
                                arguments=[

                                ]
                            ),
                            arguments=[
                                FunctionCallArgument(
                                    value=IntegerLiteral(
                                        value="100"
                                    )
                                )
                            ]
                        )
                    )
                ]
            )
        )
    ]
)
*)
