emptyList = [    ]
singleElementList = [42]
singleElementListWithTrailingComma = [
    3.14, 
]
listLiteralRetrieval = [
    10
    , 20
    , 30
][1]
listWithoutCommas = [
    1
    2
    3
    4
    5
]

multiElementList = [
    "apple",
    "banana",
    "cherry",
]
nestedLists = [
    [1, 2, 3],
    [4, 5, 6],
]
listWithExpressions = [
    1 + 2,
    3 * 4,
    5 - 6 * (8 / 2),
    8 + matrix[0][1] - vector.x,
]

simpleComprehension = [x * 2 for x in seq]
keyValueComprehension = [v for k, v in mapItems]
comprehensionWithCondition = [x for x in seq if x % 2 == 0]
multiComprehension = [
    x.name
    for xs in listOfLists
    if xs.length > 2
    for x in xs
    if x.active
]
nestedComprehension = [[y for y in x]for x in[[1, 2, 3]][0]if x % 2 == 1]

(*
Module(
    top_level_nodes=[
        VariableBindingStatement(
            name=Symbol(
                name="emptyList"
            ),
            value=ListLiteral(
                elements=[

                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="singleElementList"
            ),
            value=ListLiteral(
                elements=[
                    IntegerLiteral(
                        value="42"
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="singleElementListWithTrailingComma"
            ),
            value=ListLiteral(
                elements=[
                    FloatLiteral(
                        value="3.14"
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="listLiteralRetrieval"
            ),
            value=IndexAccess(
                collection=ListLiteral(
                    elements=[
                        IntegerLiteral(
                            value="10"
                        ),
                        IntegerLiteral(
                            value="20"
                        ),
                        IntegerLiteral(
                            value="30"
                        )
                    ]
                ),
                index=IntegerLiteral(
                    value="1"
                )
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="listWithoutCommas"
            ),
            value=ListLiteral(
                elements=[
                    IntegerLiteral(
                        value="1"
                    ),
                    IntegerLiteral(
                        value="2"
                    ),
                    IntegerLiteral(
                        value="3"
                    ),
                    IntegerLiteral(
                        value="4"
                    ),
                    IntegerLiteral(
                        value="5"
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="multiElementList"
            ),
            value=ListLiteral(
                elements=[
                    StringLiteral(
                        value="apple"
                    ),
                    StringLiteral(
                        value="banana"
                    ),
                    StringLiteral(
                        value="cherry"
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="nestedLists"
            ),
            value=ListLiteral(
                elements=[
                    ListLiteral(
                        elements=[
                            IntegerLiteral(
                                value="1"
                            ),
                            IntegerLiteral(
                                value="2"
                            ),
                            IntegerLiteral(
                                value="3"
                            )
                        ]
                    ),
                    ListLiteral(
                        elements=[
                            IntegerLiteral(
                                value="4"
                            ),
                            IntegerLiteral(
                                value="5"
                            ),
                            IntegerLiteral(
                                value="6"
                            )
                        ]
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="listWithExpressions"
            ),
            value=ListLiteral(
                elements=[
                    BinaryOperation(
                        left=IntegerLiteral(
                            value="1"
                        ),
                        operator="+",
                        right=IntegerLiteral(
                            value="2"
                        )
                    ),
                    BinaryOperation(
                        left=IntegerLiteral(
                            value="3"
                        ),
                        operator="*",
                        right=IntegerLiteral(
                            value="4"
                        )
                    ),
                    BinaryOperation(
                        left=IntegerLiteral(
                            value="5"
                        ),
                        operator="-",
                        right=BinaryOperation(
                            left=IntegerLiteral(
                                value="6"
                            ),
                            operator="*",
                            right=ParenthesizedExpression(
                                expression=BinaryOperation(
                                    left=IntegerLiteral(
                                        value="8"
                                    ),
                                    operator="/",
                                    right=IntegerLiteral(
                                        value="2"
                                    )
                                )
                            )
                        )
                    ),
                    BinaryOperation(
                        left=BinaryOperation(
                            left=IntegerLiteral(
                                value="8"
                            ),
                            operator="+",
                            right=IndexAccess(
                                collection=IndexAccess(
                                    collection=Symbol(
                                        name="matrix"
                                    ),
                                    index=IntegerLiteral(
                                        value="0"
                                    )
                                ),
                                index=IntegerLiteral(
                                    value="1"
                                )
                            )
                        ),
                        operator="-",
                        right=AttributeAccess(
                            object=Symbol(
                                name="vector"
                            ),
                            attribute=Symbol(
                                name="x"
                            )
                        )
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="simpleComprehension"
            ),
            value=ListComprehension(
                element=BinaryOperation(
                    left=Symbol(
                        name="x"
                    ),
                    operator="*",
                    right=IntegerLiteral(
                        value="2"
                    )
                ),
                clauses=[
                    ComprehensionBinding(
                        variables=[
                            Symbol(
                                name="x"
                            )
                        ],
                        iterable=Symbol(
                            name="seq"
                        )
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="keyValueComprehension"
            ),
            value=ListComprehension(
                element=Symbol(
                    name="v"
                ),
                clauses=[
                    ComprehensionBinding(
                        variables=[
                            Symbol(
                                name="k"
                            ),
                            Symbol(
                                name="v"
                            )
                        ],
                        iterable=Symbol(
                            name="mapItems"
                        )
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="comprehensionWithCondition"
            ),
            value=ListComprehension(
                element=Symbol(
                    name="x"
                ),
                clauses=[
                    ComprehensionBinding(
                        variables=[
                            Symbol(
                                name="x"
                            )
                        ],
                        iterable=Symbol(
                            name="seq"
                        )
                    ),
                    ComprehensionGuard(
                        condition=BinaryOperation(
                            left=BinaryOperation(
                                left=Symbol(
                                    name="x"
                                ),
                                operator="%",
                                right=IntegerLiteral(
                                    value="2"
                                )
                            ),
                            operator="==",
                            right=IntegerLiteral(
                                value="0"
                            )
                        )
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="multiComprehension"
            ),
            value=ListComprehension(
                element=AttributeAccess(
                    object=Symbol(
                        name="x"
                    ),
                    attribute=Symbol(
                        name="name"
                    )
                ),
                clauses=[
                    ComprehensionBinding(
                        variables=[
                            Symbol(
                                name="xs"
                            )
                        ],
                        iterable=Symbol(
                            name="listOfLists"
                        )
                    ),
                    ComprehensionGuard(
                        condition=BinaryOperation(
                            left=AttributeAccess(
                                object=Symbol(
                                    name="xs"
                                ),
                                attribute=Symbol(
                                    name="length"
                                )
                            ),
                            operator=">",
                            right=IntegerLiteral(
                                value="2"
                            )
                        )
                    ),
                    ComprehensionBinding(
                        variables=[
                            Symbol(
                                name="x"
                            )
                        ],
                        iterable=Symbol(
                            name="xs"
                        )
                    ),
                    ComprehensionGuard(
                        condition=AttributeAccess(
                            object=Symbol(
                                name="x"
                            ),
                            attribute=Symbol(
                                name="active"
                            )
                        )
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="nestedComprehension"
            ),
            value=ListComprehension(
                element=ListComprehension(
                    element=Symbol(
                        name="y"
                    ),
                    clauses=[
                        ComprehensionBinding(
                            variables=[
                                Symbol(
                                    name="y"
                                )
                            ],
                            iterable=Symbol(
                                name="x"
                            )
                        )
                    ]
                ),
                clauses=[
                    ComprehensionBinding(
                        variables=[
                            Symbol(
                                name="x"
                            )
                        ],
                        iterable=IndexAccess(
                            collection=ListLiteral(
                                elements=[
                                    ListLiteral(
                                        elements=[
                                            IntegerLiteral(
                                                value="1"
                                            ),
                                            IntegerLiteral(
                                                value="2"
                                            ),
                                            IntegerLiteral(
                                                value="3"
                                            )
                                        ]
                                    )
                                ]
                            ),
                            index=IntegerLiteral(
                                value="0"
                            )
                        )
                    ),
                    ComprehensionGuard(
                        condition=BinaryOperation(
                            left=BinaryOperation(
                                left=Symbol(
                                    name="x"
                                ),
                                operator="%",
                                right=IntegerLiteral(
                                    value="2"
                                )
                            ),
                            operator="==",
                            right=IntegerLiteral(
                                value="1"
                            )
                        )
                    )
                ]
            )
        )
    ]
)
*)
