emptyMap = {  }
simpleMap = { key1 = "value1"
    , key2 = 42
    , key3 = False }
mapWithoutCommas =
    {
        a = 1
        b = 2
        c = 3
    }
nestedMap = {
    outerKey1 = {
        innerKey1 = "innerValue1",
        innerKey2 = 3.14
    },
    outerKey2 = [1, 2, 3]
}
mapWithExpressions = {
    sumKey = 10 + 20,
    ["concat" + "Key"] = "Hello, " + "world!"
}
mapComprehension = { k = v * 2 for k, v in someMap if v > 10 }
nestedComprehension = { k = { subK = subV for subK, subV in v } for k, v in anotherMap }

(*
Module(
    top_level_nodes=[
        VariableBindingStatement(
            name=Symbol(
                name="emptyMap"
            ),
            value=MapLiteral(
                entries=[

                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="simpleMap"
            ),
            value=MapLiteral(
                entries=[
                    Entry(
                        key=Symbol(
                            name="key1"
                        ),
                        value=StringLiteral(
                            value="value1"
                        )
                    ),
                    Entry(
                        key=Symbol(
                            name="key2"
                        ),
                        value=IntegerLiteral(
                            value="42"
                        )
                    ),
                    Entry(
                        key=Symbol(
                            name="key3"
                        ),
                        value=Symbol(
                            name="False"
                        )
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="mapWithoutCommas"
            ),
            value=MapLiteral(
                entries=[
                    Entry(
                        key=Symbol(
                            name="a"
                        ),
                        value=IntegerLiteral(
                            value="1"
                        )
                    ),
                    Entry(
                        key=Symbol(
                            name="b"
                        ),
                        value=IntegerLiteral(
                            value="2"
                        )
                    ),
                    Entry(
                        key=Symbol(
                            name="c"
                        ),
                        value=IntegerLiteral(
                            value="3"
                        )
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="nestedMap"
            ),
            value=MapLiteral(
                entries=[
                    Entry(
                        key=Symbol(
                            name="outerKey1"
                        ),
                        value=MapLiteral(
                            entries=[
                                Entry(
                                    key=Symbol(
                                        name="innerKey1"
                                    ),
                                    value=StringLiteral(
                                        value="innerValue1"
                                    )
                                ),
                                Entry(
                                    key=Symbol(
                                        name="innerKey2"
                                    ),
                                    value=FloatLiteral(
                                        value="3.14"
                                    )
                                )
                            ]
                        )
                    ),
                    Entry(
                        key=Symbol(
                            name="outerKey2"
                        ),
                        value=ListLiteral(
                            elements=[
                                IntegerLiteral(
                                    value="1"
                                ),
                                IntegerLiteral(
                                    value="2"
                                ),
                                IntegerLiteral(
                                    value="3"
                                )
                            ]
                        )
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="mapWithExpressions"
            ),
            value=MapLiteral(
                entries=[
                    Entry(
                        key=Symbol(
                            name="sumKey"
                        ),
                        value=BinaryOperation(
                            left=IntegerLiteral(
                                value="10"
                            ),
                            operator="+",
                            right=IntegerLiteral(
                                value="20"
                            )
                        )
                    ),
                    Entry(
                        key=BinaryOperation(
                            left=StringLiteral(
                                value="concat"
                            ),
                            operator="+",
                            right=StringLiteral(
                                value="Key"
                            )
                        ),
                        value=BinaryOperation(
                            left=StringLiteral(
                                value="Hello, "
                            ),
                            operator="+",
                            right=StringLiteral(
                                value="world!"
                            )
                        )
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="mapComprehension"
            ),
            value=MapComprehension(
                key=Symbol(
                    name="k"
                ),
                value=BinaryOperation(
                    left=Symbol(
                        name="v"
                    ),
                    operator="*",
                    right=IntegerLiteral(
                        value="2"
                    )
                ),
                clauses=[
                    ComprehensionBinding(
                        variables=[
                            Symbol(
                                name="k"
                            ),
                            Symbol(
                                name="v"
                            )
                        ],
                        iterable=Symbol(
                            name="someMap"
                        )
                    ),
                    ComprehensionGuard(
                        condition=BinaryOperation(
                            left=Symbol(
                                name="v"
                            ),
                            operator=">",
                            right=IntegerLiteral(
                                value="10"
                            )
                        )
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="nestedComprehension"
            ),
            value=MapComprehension(
                key=Symbol(
                    name="k"
                ),
                value=MapComprehension(
                    key=Symbol(
                        name="subK"
                    ),
                    value=Symbol(
                        name="subV"
                    ),
                    clauses=[
                        ComprehensionBinding(
                            variables=[
                                Symbol(
                                    name="subK"
                                ),
                                Symbol(
                                    name="subV"
                                )
                            ],
                            iterable=Symbol(
                                name="v"
                            )
                        )
                    ]
                ),
                clauses=[
                    ComprehensionBinding(
                        variables=[
                            Symbol(
                                name="k"
                            ),
                            Symbol(
                                name="v"
                            )
                        ],
                        iterable=Symbol(
                            name="anotherMap"
                        )
                    )
                ]
            )
        )
    ]
)
*)
