simpleSet = { value1, "value1", value2, 42, value3, False }
setWithoutCommas =
    {
        a
        1
        b
        2
        c
        3
    }
nestedSet = {
    {
        innerKey1 = "innerValue1",
        innerKey2 = 3.14
    }
    [1, 2, 3]
}
setWithExpressions = {
    10 + 20,
    ["concat" + "Value"],
    "Hello, " + "world!",
}
setComprehension = { v * 2 for k, v in someMap if v > 10 }
nestedComprehension = { { subK = subV for subK, subV in v } for k, v in anotherMap }

(*
Module(
    top_level_nodes=[
        VariableBindingStatement(
            name=Symbol(
                name="simpleSet"
            ),
            value=SetLiteral(
                elements=[
                    Symbol(
                        name="value1"
                    ),
                    StringLiteral(
                        value="value1"
                    ),
                    Symbol(
                        name="value2"
                    ),
                    IntegerLiteral(
                        value="42"
                    ),
                    Symbol(
                        name="value3"
                    ),
                    Symbol(
                        name="False"
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="setWithoutCommas"
            ),
            value=SetLiteral(
                elements=[
                    Symbol(
                        name="a"
                    ),
                    IntegerLiteral(
                        value="1"
                    ),
                    Symbol(
                        name="b"
                    ),
                    IntegerLiteral(
                        value="2"
                    ),
                    Symbol(
                        name="c"
                    ),
                    IntegerLiteral(
                        value="3"
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="nestedSet"
            ),
            value=SetLiteral(
                elements=[
                    MapLiteral(
                        entries=[
                            Entry(
                                key=Symbol(
                                    name="innerKey1"
                                ),
                                value=StringLiteral(
                                    value="innerValue1"
                                )
                            ),
                            Entry(
                                key=Symbol(
                                    name="innerKey2"
                                ),
                                value=FloatLiteral(
                                    value="3.14"
                                )
                            )
                        ]
                    ),
                    ListLiteral(
                        elements=[
                            IntegerLiteral(
                                value="1"
                            ),
                            IntegerLiteral(
                                value="2"
                            ),
                            IntegerLiteral(
                                value="3"
                            )
                        ]
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="setWithExpressions"
            ),
            value=SetLiteral(
                elements=[
                    BinaryOperation(
                        left=IntegerLiteral(
                            value="10"
                        ),
                        operator="+",
                        right=IntegerLiteral(
                            value="20"
                        )
                    ),
                    ListLiteral(
                        elements=[
                            BinaryOperation(
                                left=StringLiteral(
                                    value="concat"
                                ),
                                operator="+",
                                right=StringLiteral(
                                    value="Value"
                                )
                            )
                        ]
                    ),
                    BinaryOperation(
                        left=StringLiteral(
                            value="Hello, "
                        ),
                        operator="+",
                        right=StringLiteral(
                            value="world!"
                        )
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="setComprehension"
            ),
            value=SetComprehension(
                element=BinaryOperation(
                    left=Symbol(
                        name="v"
                    ),
                    operator="*",
                    right=IntegerLiteral(
                        value="2"
                    )
                ),
                clauses=[
                    ComprehensionBinding(
                        variables=[
                            Symbol(
                                name="k"
                            ),
                            Symbol(
                                name="v"
                            )
                        ],
                        iterable=Symbol(
                            name="someMap"
                        )
                    ),
                    ComprehensionGuard(
                        condition=BinaryOperation(
                            left=Symbol(
                                name="v"
                            ),
                            operator=">",
                            right=IntegerLiteral(
                                value="10"
                            )
                        )
                    )
                ]
            )
        ),
        VariableBindingStatement(
            name=Symbol(
                name="nestedComprehension"
            ),
            value=SetComprehension(
                element=MapComprehension(
                    key=Symbol(
                        name="subK"
                    ),
                    value=Symbol(
                        name="subV"
                    ),
                    clauses=[
                        ComprehensionBinding(
                            variables=[
                                Symbol(
                                    name="subK"
                                ),
                                Symbol(
                                    name="subV"
                                )
                            ],
                            iterable=Symbol(
                                name="v"
                            )
                        )
                    ]
                ),
                clauses=[
                    ComprehensionBinding(
                        variables=[
                            Symbol(
                                name="k"
                            ),
                            Symbol(
                                name="v"
                            )
                        ],
                        iterable=Symbol(
                            name="anotherMap"
                        )
                    )
                ]
            )
        )
    ]
)
*)
